version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/back"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"

  - package-ecosystem: "npm"
    directory: "/front"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"